version: '3.9'

services:
  webserver:
    container_name: nginx
    image: nginx:latest
    restart: always
    depends_on:
      - server
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - /root/fastpaws/nginx/nginx.conf:/etc/nginx/nginx.conf
      - /root/fastpaws/nginx/conf:/etc/nginx/conf.d
      - /etc/letsencrypt:/etc/letsencrypt
    networks:
      - fastpaws

  server:
    container_name: fastpaws-server
    image: fastpaws-server
    depends_on:
      - postgres
    build:
      context: .
      dockerfile: Dockerfile.server
      args:
        SERVER_PORT: ${SERVER_PORT}
    restart: always
    ports:
      - '${SERVER_PORT}:${SERVER_PORT}'
    environment:
      SERVER_PORT: ${SERVER_PORT}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_HOST: postgres
      REDIRECT_URL: host.docker.internal
    command: sh -c "echo '  ➜ ⏳ Waiting for ${POSTGRES_DB}...' && ./wait-for.sh postgres:${POSTGRES_PORT} -- node /app/index.js"
    # command: sh -c "node /app/index.js"
    networks:
      - fastpaws

  postgres:
    container_name: postgres
    image: postgres:15.3
    restart: always
    ports:
      - '${POSTGRES_PORT}:5432'
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d
    networks:
      - fastpaws

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:7.1
    restart: always
    depends_on:
      - postgres
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      PGADMIN_LISTEN_PORT: ${PGADMIN_LISTEN_PORT}
    ports:
      - "${PGADMIN_PORT}:${PGADMIN_LISTEN_PORT}"
    networks:
      - fastpaws

networks:
  fastpaws:
    name: fastpaws-network
