version: '3.9'

services:
  webserver:
    container_name: nginx
    image: nginx:1.25
    restart: always
    depends_on:
      - server
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf/:/etc/nginx/conf.d/
      - certbot/www:/var/www/certbot/
      - certbot/conf:/etc/letsencrypt/
    networks:
      - fastpaws
  
  certbot:
    image: certbot/certbot:latest
    container_name: certbot
    volumes:
      - certbot/www:/var/www/certbot/
      - certbot/conf:/etc/letsencrypt/
    depends_on:
      - webserver
    command: certonly --webroot --webroot-path=/var/www/certbot/ --email example@example.com --agree-tos --no-eff-email --staging -d fast-paws.ya-praktikum.tech  -d www.fast-paws.ya-praktikum.tech

  server:
    container_name: fastpaws-server
    image: fastpaws-server
    depends_on:
      - postgres
    build:
      context: .
      dockerfile: Dockerfile.server
      args:
        SERVER_PORT: ${SERVER_PORT}
    restart: always
    ports:
      - '${SERVER_PORT}:${SERVER_PORT}'
    environment:
      SERVER_PORT: ${SERVER_PORT}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PORT: ${POSTGRES_PORT}
      # POSTGRES_HOST: host.docker.internal
      POSTGRES_HOST: postgres
    # command: sh -c "echo '  ➜ ⏳ Waiting for ${POSTGRES_DB}...' && ./wait-for.sh postgres:${POSTGRES_PORT} -- node /app/index.js"
    command: sh -c "node /app/index.js"
    networks:
      - fastpaws

  postgres:
    container_name: postgres
    image: postgres:15.3
    restart: always
    ports:
      - '${POSTGRES_PORT}:${POSTGRES_PORT}'
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d
      - ./tmp/pgdata:/var/lib/postgresql/data
    networks:
      - fastpaws

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:7.1
    restart: always
    depends_on:
      - postgres
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_LISTEN_PORT: 80
    ports:
      - '8080:8080'
    networks:
      - fastpaws

networks:
  fastpaws:
    name: fastpaws-network
